import styled from "styled-components";
import mixins from "../../styles/_mixins";
import variables from "../../styles/_variables";
import ReadMore from "../ReadMore";
import GenesisGenerationData from "./GenesisGenerationData";

const { media } = mixins;
const { dark } = mixins;
const {
    colors: { blue, neutrals },
    typography: { captionBold1, caption1 },
} = variables;

export default function GenesisSidebarInfo() {
    return (
        <Container>
            <GenesisSidebarDescription>
                <strong>FREE</strong> Daily WoV Token
            </GenesisSidebarDescription>

            <GenesisSidebarContent>
                <ReadMore withToggle>
                    WoV token are generated by your World of V cards: based on
                    the number of cards minted, each holder will generate daily
                    WoV tokens consistent with the level of the card owned.
                    There are two main categories of WoV Cards: the Genesis 2021
                    Cards and the Special Cards.
                </ReadMore>

                <br />

                <strong>Generate WoV every day:</strong>
            </GenesisSidebarContent>

            {GenesisGenerationData.map(({ generationAmount, cardType, name }) =>
                generationAmount > 0 && cardType === "Special" ? (
                    <GenesisSidebarItem key={name}>
                        <h4>{name === "X Node" ? "X-Node" : name} Cards</h4>
                        <span>{generationAmount}</span> WoV per day
                    </GenesisSidebarItem>
                ) : null
            )}
        </Container>
    );
}

const Container = styled.div`
    border-radius: 16px;
    box-shadow: 0px 40px 32px -24px rgba(15, 15, 15, 0.12);
    background: ${neutrals[8]};
    border: 1px solid ${neutrals[6]};
    text-align: center;
    padding: 16px 28px 24px;
    margin-top: 16px;
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
    gap: 16px;
    row-gap: 16px;
    grid-gap: 16px;

    ${dark`
        background: ${neutrals[2]};
        border-color: ${neutrals[3]};
    `};

    ${media.t`
        flex-direction: inherit;
    `}
`;

const GenesisSidebarDescription = styled.div`
    ${caption1}
    text-align: center;
    width: 100%;
`;

const GenesisSidebarContent = styled.div``;

const GenesisSidebarItem = styled.div`
    color: ${blue};
    ${captionBold1};
    font-weight: 800;

    & > h4 {
        margin-bottom: 6px;
        color: ${neutrals[1]};

        ${dark`
            color: ${neutrals[8]};
        `}
    }

    & > span {
        height: 40px;
        border-radius: 20px;
        font-size: 14px;
        background-color: ${blue};
        color: white;
        font-weight: bold;
        padding: 5px 15px;
        margin-right: 3px;
    }

    ${media.t`
        flex: 1 1 150px;
    `}
`;
