import {
    BusinessClaimPageContent,
    BusinessClaimPageContentProps,
} from "@/components/business/BusinessClaimPageContent";
import Head from "@/components/Head";
import type { NextPage, NextPageContext } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const BusinessClaim: NextPage<BusinessClaimPageContentProps> = (props) => {
    return (
        <>
            <Head title="Claim your FREE NFT" />
            <BusinessClaimPageContent {...props} />
        </>
    );
};

export async function getServerSideProps(context: NextPageContext) {
    const slug = context.query?.slug as string;
    const locale = context.locale || "en";

    if (pages[slug] == null) {
        return { redirect: { destination: "/" } };
    }

    return {
        props: {
            ...pages[slug],
            slug,
            locale,
            ...(await serverSideTranslations(locale, [
                "business_claim",
                "connect_step",
                "business_countdown",
                "common",
                "recaptcha_banner",
            ])),
        },
    };
}

export default BusinessClaim;

const pages: Record<string, Omit<BusinessClaimPageContentProps, "slug">> = {
    artemix: {
        pointsContractAddress: "0x633cd60DC3D1598503411A2Ea550a23ed36B6e82",
        nftImgUrl: "/img/nft__artemix.png",
        nftName: "NFT",
        isSingleClaim: true,
        logoUrlLight: "/img/logo__artemix.png",
        logoUrlDark: "/img/logo__artemix--white.png",
        bannerUrlMobile: "/img/cover-banner.png",
        bannerUrlDesktop: "/img/cover-banner.png",
        clientId: "artemix_test_1",
    },
    mitsuba: {
        pointsContractAddress: "0x54b1375BddF4119940A76AF4Fc48Cd58958DAa5D",
        nftImgUrl: "/img/nft__mitsuba.jpg",
        nftName: "NFT",
        logoUrlLight: "/img/logo__mitsuba.png",
        logoUrlDark: "/img/logo__mitsuba--white.png",
        bannerUrlMobile: "/img/bg__mitsuba.jpg",
        bannerUrlDesktop: "/img/bg__mitsuba.jpg",
        clientId: "mitsuba_test_1",
        isPOAToken: false,
    },
    ufc: {
        pointsContractAddress: "0xa810237745b776aeB42181d2097bAa50ACEd7D8a",
        nftImgUrl: "/img/nft__ufc.jpg",
        nftName: "Phygital",
        logoUrlLight: "/img/logo__ufc.png",
        logoUrlDark: "/img/logo__ufc.png",
        bannerUrlMobile: "/img/bg__ufc.jpg",
        bannerUrlDesktop: "/img/bg__ufc.jpg",
        clientId: "ufc_test_1",
        isPOAToken: false,
    },
    vechain2023: {
        pointsContractAddress: "0xa542c0875b6f5EBeFe57AA00CA56A4d19904C0b4",
        titleStrong: "VeChain Summit 2023",
        nftImgUrl: "/img/nft__vechain2023.png",
        nftName: "POA NFT",
        isSingleClaim: true,
        logoUrlLight: "/img/vechain__logo.png",
        logoUrlDark: "/img/vechain__logo--white.png",
        bannerUrlMobile: "/img/bg__vechain2023.jpg",
        bannerUrlDesktop: "/img/bg__vechain2023.jpg",
        clientId: "vechain2023_test_1",
    },
    nftloyaltytest: {
        pointsContractAddress: "",
        nftImgUrl: "/img/nft__schecker.png",
        nftName: "RAW Point",
        logoUrlLight: "/img/logo__schecker--white.png",
        logoUrlDark: "/img/logo__schecker.png",
        bannerUrlMobile: "/img/schecker__banner--desktop.png",
        bannerUrlDesktop: "/img/schecker__banner--desktop.png",
        clientId: "scheckter_t3",
        selectOptions: [
            { label: "HEARTY APPLE NUT OATS", id: "hearty_apple_nut_oats" },
            { label: "AYUVEDIC KITCHARI", id: "ayuvedic_kitchari" },
            { label: "THE QUICHE", id: "the_quiche" },
            { label: "NATURELLA CREPE", id: "naturella_crepe" },
            {
                label: "FAMOUS PUMPKIN PIE FLAPJACKS",
                id: "famous_pumpkin_pie_flapjacks",
            },
            { label: "KNICKERS SMOOTHIE", id: "knickers_smoothie" },
            { label: "SUNDRIED TOMATO ZOODLES", id: "sundried_tomato_zoodles" },
        ],
    },
    scheckter: {
        pointsContractAddress: "0x5D431bc82b67C070639E747c50A13CfF15403F18",
        nftImgUrl: "/img/nft__schecker.png",
        nftName: "RAW Point",
        logoUrlLight: "/img/logo__schecker--white.png",
        logoUrlDark: "/img/logo__schecker.png",
        bannerUrlMobile: "/img/schecker__banner--desktop.png",
        bannerUrlDesktop: "/img/schecker__banner--desktop.png",
        clientId: "scheckter_official",
        validChars: "0-9a-zA-Z",
        codeLength: 8,
        optionsLabel: "Pick your favorite dish",
        selectOptions: [
            { label: "HEART APPLE NUT OATS", id: "heart_apple_nut_oats" },
            { label: "AYURVEDA KITCHARI", id: "ayurveda_kitchari" },
            { label: "THE QUICHE", id: "the_quiche" },
            { label: "AVO TOAST", id: "avo_toast" },
            { label: "NATURELLA CREPÊ", id: "naturella_crepe" },
            {
                label: "FAMOUS PUMPKIN PIE FLAPJACKS",
                id: "famous_pumpkin_pie_flapjacks",
            },
            { label: "SUNDRIED TOMATO ZOODLES", id: "sundried_tomato_zoodles" },
            { label: "GUT HEALING BOWL", id: "gut_healing_bowl" },
            { label: "THE OPEN SANDWICH", id: "the_open_sandwich" },
            { label: "SWEET POTATO GNOCCHI", id: "sweet_potato_gnocchi" },
            { label: "THE FEEL-GOOD WRAP", id: "the_feel_good_wrap" },
            { label: "FAMOUS FALAFEL WRAP", id: "famous_falafel_wrap" },
            { label: "THE DOG", id: "the_dog" },
            {
                label: "THE SCHECKTER'S RAW BURGER",
                id: "the_scheckters_raw burger",
            },
        ],
        loginTitle: {
            en: "Welcome to Scheckter's RAW NFT Loyalty Program!",
            it: "Welcome to Scheckter's RAW NFT Loyalty Program!",
        },
    },
    "wine-test": {
        pointsContractAddress: "0x32abb85A818E5D1eBA42F1288D34976EB6DccBdE",
        nftImgUrl: "/img/business_montezemolo_nft_image.jpg",
        nftName: "Point",
        // logoUrlLight: "N/A",
        // logoUrlDark: "N/A",
        bannerUrlMobile: "/img/business_montezemolo_banner.jpg",
        bannerUrlDesktop: "/img/business_montezemolo_banner.jpg",
        clientId: "Wine_test_1",
        selectOptions: [
            { label: "Chardonnay", id: "chardonnay" },
            { label: "Pinot Grigio", id: "pinot_grigio" },
            { label: "Sauvignon Blanc", id: "sauvignon_blanc" },
            { label: "Pinot Noir", id: "pinot_noir" },
            { label: "Merlot", id: "merlot" },
        ],
    },
    Sweat1000: {
        pointsContractAddress: "0xC40BC08aF312ca03592a54F96fB34c10bd10Cb37",
        nftImgUrl: "/img/business_sweat_1000_nft_image.jpg",
        nftName: "SWEAT NFT",
        logoUrlLight: "/img/business_logo_sweat1000_light.png",
        logoUrlDark: "/img/business_logo_sweat1000_dark.png",
        bannerUrlMobile: "/img/business_sweat_1000_banner.png",
        bannerUrlDesktop: "/img/business_sweat_1000_banner.png",
        clientId: "Gym_test_1",
        validChars: "0-9a-zA-Z",
        codeLength: 8,
        optionsLabel: "How many SWEAT 1000 classes do you attend per week?",
        selectOptions: [
            { label: "1", id: "1" },
            { label: "2", id: "2" },
            { label: "3", id: "3" },
            { label: "4", id: "4" },
            { label: "5", id: "5" },
            { label: "6", id: "6" },
            { label: "7", id: "7" },
        ],
    },
    BIANCHET: {
        pointsContractAddress: "0x19420900Aef05B4fC5453c51B93585F3cB20799a",
        nftImgUrl: "/img/business_bianchet_nft_img.jpg",
        nftName: "BIANCHET",
        // logoUrlLight: "N/A",
        // logoUrlDark: "N/A",
        bannerUrlMobile: "/img/business_bianchet_banner.jpg",
        bannerUrlDesktop: "/img/business_bianchet_banner.jpg",
        clientId: "BIANCHET_test_1",
        selectOptions: [
            { label: "Orange Tourbillon", id: "orange_tourbillon" },
            { label: "Ocean Blue", id: "ocean_blue" },
            { label: "Red Tourbillon", id: "red_tourbillon" },
            { label: "Carbon Earth Tourbillon", id: "carbon_earth_tourbillon" },
        ],
        optionsLabel: "option",
        showDashboardButton: false,
    },
    "Crossfit-Mediolanvm": {
        pointsContractAddress: "0xE045F9D4654D7EA0230aa7a36DD9d6A2D486f237",
        nftImgUrl: "/img/business_crossfit_nft_image.jpeg",
        nftName: "Mediolanvm Awards NFT",
        // logoUrlLight: "N/A",
        // logoUrlDark: "N/A",
        bannerUrlMobile: "/img/business_crossfit_banner.jpeg",
        bannerUrlDesktop: "/img/business_crossfit_banner.jpeg",
        clientId: "Crossfit_test1",
        validChars: "0-9a-zA-Z",
        codeLength: 8,
        optionsLabel: "What’s your favorite Exercise?",
        selectOptions: [
            { label: "Snatch", id: "snatch" },
            { label: "Clean", id: "clean" },
            { label: "Burpees", id: "burpees" },
            { label: "Pull Ups", id: "pull_ups" },
            { label: "Bar Muscle Up", id: "bar_muscle_up" },
            { label: "Toes To Bar", id: "toes_to_bar" },
            { label: "Double Unders", id: "double_unders" },
            { label: "HSPU", id: "hspu" },
        ],
        showDashboardButton: false,
        showBirthDate: true,
    },
    EFN: {
        pointsContractAddress: "0xa0d19EB33D80Cefef1d6F03F77151133316ad548",
        nftImgUrl: "/img/business_efn_nft_image.jpg",
        nftName: "Elite Fight Night",
        titleStrong: "",
        isSingleClaim: true,
        // logoUrlLight: "N/A",
        // logoUrlDark: "N/A",
        bannerUrlMobile: "/img/business_efn_banner.png",
        bannerUrlDesktop: "/img/business_efn_banner.png",
        clientId: "EFN-T1",
        validChars: "0-9a-zA-Z",
        codeLength: 8,
        optionsLabel: "What fighter are you coming to watch?",
        selectOptions: [
            { label: "Sherman Lovely", id: "Sherman Lovely" },
            { label: "Konnor Kuppe", id: "Konnor Kuppe" },
            { label: "Brandon Zimmerman", id: "Brandon Zimmerman" },
            { label: "Emanuel Pugh", id: "Emanuel Pugh" },
            { label: "Agustin Bahena", id: "Agustin Bahena" },
            { label: "Marco McDonald", id: "Marco McDonald" },
            { label: "Steven Mihajlovich", id: "Steven Mihajlovich" },
            { label: "Jalan Gibson", id: "Jalan Gibson" },
            { label: "Cesar Ortega", id: "Cesar Ortega" },
            { label: "Juan Avila", id: "Juan Avila" },
            { label: "Alex Delgado", id: "Alex Delgado" },
            { label: "Alex Moscosa", id: "Alex Moscosa" },
            { label: "Dom Aquino", id: "Dom Aquino" },
            { label: "Patrick Jackson", id: "Patrick Jackson" },
            { label: "Cameron Cook", id: "Cameron Cook" },
            { label: "Tim Noverini", id: "Tim Noverini" },
            {
                label: "Kelsey IversValanti Atsas",
                id: "Kelsey IversValanti Atsas",
            },
            { label: "Tyler Scott", id: "Tyler Scott" },
            { label: "Jonathon Appelman", id: "Jonathon Appelman" },
            { label: "Yair Jasso", id: "Yair Jasso" },
            { label: "Duvellasha Lee Jr.", id: "Duvellasha Lee Jr." },
            { label: "JJ Johnson", id: "JJ Johnson" },
            { label: "Taylor Burley", id: "Taylor Burley" },
            { label: "Bryce Woener", id: "Bryce Woener" },
            { label: "Zak Hassan", id: "Zak Hassan" },
            { label: "Diego Martinez", id: "Diego Martinez" },
            { label: "David Sandoval", id: "David Sandoval" },
            { label: "Bryshon Heads", id: "Bryshon Heads" },
            { label: "Mouhamed Cisse", id: "Mouhamed Cisse" },
            { label: "Merrick Babcock", id: "Merrick Babcock" },
            { label: "Alex Moore IV", id: "Alex Moore IV" },
            { label: "Bobby Kelley", id: "Bobby Kelley" },
            { label: "Veronyka Soeurmau", id: "Veronyka Soeurmau" },
            { label: "Valanti Atsas", id: "Valanti Atsas" },
        ],
        showDashboardButton: false,
    },
    gigidatome: {
        pointsContractAddress: "0xA3aC5FCC4fAB797bb3e748f0acc59f1D844C48fc",
        nftImgUrl: "/img/business_gigidatome_nft_image.jpg",
        nftName: '"Il Gigante Del Campetto" di Gigi Datome!',
        // nftNameStrong: true,
        titleStrong: "",
        logoUrlLight: "/img/explus__logo.png",
        logoUrlDark: "/img/explus__logo--white.png",
        bannerUrlMobile: "/img/business_gigidatome_banner.png",
        bannerUrlDesktop: "/img/business_gigidatome_banner.png",
        clientId: "codeless",
        validChars: "0-9a-zA-Z",
        isSingleClaim: true,
        showDashboardButton: false,
        loginTitle: {
            en: 'Receive the free NFT <strong>"Il Gigante Del Campetto"</strong> by Gigi Datome!',
            it: 'Ricevi l’NFT gratuito <strong>"Il Gigante Del Campetto"</strong> di Gigi Datome!',
        },
    },
    VeSmash: {
        pointsContractAddress: "0x146C97db8921Fbaf1F005577C02E6748922F2685",
        nftImgUrl: "/img/business_vesmash_nft_image.jpg",
        nftName: "VeSmash",
        nftNameStrong: true,
        logoUrlLight: "/img/vechain__logo.png",
        logoUrlDark: "/img/vechain__logo--white.png",
        bannerUrlMobile: "/img/business_vesmash_banner.png",
        bannerUrlDesktop: "/img/business_vesmash_banner.png",
        clientId: "codeless",
        showDashboardButton: false,
        titleStrong: "",
        isSingleClaim: true,
        loginTitle: {
            en: "Claim your <strong>VeSmash</strong> to win a once-in-a-lifetime experience at Internazionali",
            it: "Riscatta il tuo <strong>VeSmash</strong> per vincere un'esperienza da sogno agli Internazionali",
        },
    },
};
